# Minimal profile for dbt compile. To compile without a real database, use this directory as DBT_PROFILES_DIR.
# E.g.: DBT_PROFILES_DIR=. dbt compile
default:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ":memory:"
